name: Build image on commit to master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [ labeled, unlabeled, opened, synchronize, reopened ]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/applicationset
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17.6'
      - uses: actions/checkout@master
        with:
          path: src/applicationset

      # Build the image
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: |
          IMAGE_PLATFORMS=linux/arm64
          echo "Building image for platforms: $IMAGE_PLATFORMS"
          make image DOCKER_PUSH=false CONTAINER_REGISTRY=docker.io IMAGE_NAMESPACE=baloisemichaelmuehlebach IMAGE_TAG=v0.4.1 IMAGE_PLATFORMS=${IMAGE_PLATFORMS}
        working-directory: ./src/applicationset


      # Publish the image
      - run: |
          docker login docker.io --username baloisemichaelmuehlebach --password $PASSWORD
          docker push docker.io/baloisemichaelmuehlebach/argocd-applicationset:v0.4.1
        if: github.event_name == 'push'
        env:
          PASSWORD: ${{ secrets.TOKEN }}
